### ISSUE TITLE
[BUG]: get_bundle AttributeError: _path

### ISSUE THREAD

**Issue by jrjohn** [felix-zenk/ResourceBundle#2] opened 2022-10-26 13:27 UTC
**Describe the bug**
resourcebundle==2.0.1

self.bundle = rb.get_bundle(bundle_name="cloud", locale=language_code+"_"+country_code,path=locale_dir) 

File "/usr/local/lib/python3.8/site-packages/ResourceBundle/__init__.py", line 160, in get_bundle
return ResourceBundle(extracted_name, extracted_locale, path=path)
File "/usr/local/lib/python3.8/site-packages/ResourceBundle/__init__.py", line 64, in __init__
self._parent: ResourceBundle | None = self._get_parent_bundle()
File "/usr/local/lib/python3.8/site-packages/ResourceBundle/__init__.py", line 97, in _get_parent_bundle
return ResourceBundle(self._name, parent_locale, path=self._path)
AttributeError: _path

**To Reproduce**
call get_bundle(bundle_name="cloud", locale=language_code+"_"+country_code,path=locale_dir)  with specific path

**Additional context**
class ResourceBundle(object):
    """
    A ResourceBundle manages internationalization of string resources
    """
    __cached_bundles = dict()

    __slots__ = ["_name", "_locale", "_parent", "_mapping", "_path"]

    def __init__(self, bundle_name: str, bundle_locale: str | None, *, path: str | PathLike = None) -> None:
        self._name: str = bundle_name
        self._locale: str | None = bundle_locale
        self._parent: ResourceBundle | None = self._get_parent_bundle().  <== Exception here, because self._path not assigned.
        self._path = path
        self._mapping: dict[str, str] = self._map(path=self._path)
        # Save self in cache
        self.__cached_bundles[self.name] = self

need change to:
class ResourceBundle(object):
    """
    A ResourceBundle manages internationalization of string resources
    """
    __cached_bundles = dict()

    __slots__ = ["_name", "_locale", "_parent", "_mapping", "_path"]

    def __init__(self, bundle_name: str, bundle_locale: str | None, *, path: str | PathLike = None) -> None:
        self._name: str = bundle_name
        self._locale: str | None = bundle_locale
        self._path = path  #===== it's assigned now
        self._parent: ResourceBundle | None = self._get_parent_bundle()
        self._mapping: dict[str, str] = self._map(path=self._path)
        # Save self in cache
        self.__cached_bundles[self.name] = self

**Comment by felix-zenk** [comment] 2022-10-26 13:51
Duplicate of issue #1 
Has been resolved in version 2.0.2

**Closed as completed by felix-zenk** 2022-10-26 13:51 UTC
Labels: bug, duplicate
